### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#1]
How do you install and run this?  I appears to be uncompiled/source code.  what is required to make this run?

**Comment by TRex22** [comment]
There is a compiled release package: https://github.com/M4GNV5/NINSS/releases

**Comment by suresttexas00** [comment]
Thanks..
OK, I have it running, BUT:
I can't seem to set the memory options for startup.  I attempted to edit the file "\plugins\configs\NINSS.xml" where it says:
  
  <JavaArguments>-jar %jar% nogui</JavaArguments>

I changed it to something like 
 <JavaArguments>-Xms1024 - Xmx-1024 -jar %jar% nogui</JavaArguments>
..which causes the program to hang and never start up.

I also tried typing java in the console but it says command not recognized.

Date: Sat, 6 Dec 2014 02:29:43 -0800

**Comment by M4GNV5** [comment]
your java arguments arent valid...
to limit the ressources the server is allowed to use you can write
`-Xmx1024M -jar %jar% nogui` what would limit it to 1024MB = 1GB
You wrote `-Xmx-1024` what is missing the unit and the - shouldnt be there

But you are right if the java arguments are invalid just nothing happens :relieved:

Furthermore if it says command not found in the console you have to add your java path to the PATH variable as explained here https://www.java.com/en/download/help/path.xml

**Comment by suresttexas00** [comment]
I already have Java in the windows path, so it is probably the typo with the dash...

**Comment by suresttexas00** [comment]
Here is what I get now; program still hangs with no further output:
Loading Plugins!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\JavascriptConnec
tor.dll
No Javascript Plugins found!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\Noesis.Javascrip
t.dll
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\SimplePermission
s.dll
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\UuidConnector.dl
l
Could not load Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\UuidConne
ctor.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the ta
rget of an invocation.
Stacktrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOn
ly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandle& ctor, Boolean& b
NeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean fillCach
e)
   at System.RuntimeType.CreateInstanceImpl(Boolean publicOnly, Boolean skipVisi
bilityChecks, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NINSS.PluginManager.LoadPlugin(String file)
InnerException: Name cannot begin with the '4' character, hexadecimal value 0x34
. Line 4, position 4.
Inner Stacktrace:
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset
, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese
rveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at NINSS.API.Config.LoadConfig(String name)
   at NINSS.API.Config..ctor(String name)
   at UuidConnector.UuidConnector.LoadUuids()
   at UuidConnector.UuidConnector..ctor()
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\WebUI.dll
Finished Loading Plugins!
Plugins: 3
Starting java with arguments: -Xmx1024 -jar "C:\Users\Minecraft\Desktop\NINSSVan
illa\minecraft_server.1.8.1.jar" nogui

I wish I could see the whole command instead of the "Starting java with..."

The run.bat file I would normally use to start this server uses the following command line:

java -d64 -Xms512M -Xmx1024M -jar minecraft_server.1.8.1.jar nogui

(I will expand the memory once it goes "live")

Date: Sun, 7 Dec 2014 04:47:13 -0800

**Comment by M4GNV5** [comment]
again: you need to give minecraft a unit...
`-Xmx1024` could mean 1024 KB or 1024 MB or 1024 GB so `-Xmx1024` is invalid correctly it must be `-Xmx1024M`

The full command is `java <arguments>` so if it tells you `-Xmx1024 -jar "C:\Users\Minecraft\Desktop\NINSSVanilla\minecraft_server.1.8.1.jar" nogui` the whole command is `java -Xmx1024 -jar "C:\Users\Minecraft\Desktop\NINSSVanilla\minecraft_server.1.8.1.jar`

so the correct NINNS config representing your run.bat would be

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <!-- Server.jar file. %auto% only works with one file!-->
  <ServerFile>%auto%</ServerFile>
  <!--Java installation path. Use java.exe (for other version/64 bit use the full path) for default under windows and java under linux/mac-->
  <JavaExecutable>java.exe</JavaExecutable>
  <!-- Java arguments type java in console for help with arguments!-->
  <JavaArguments>-d64 -Xms512M -Xmx1024M -jar %jar% nogui</JavaArguments>
  <!-- Wheter Plugns are enabled or not. Default: true, NINSS doesnt make much sense without plugins-->
  <EnablePlugins>true</EnablePlugins>
  <!-- If true you wont be able to read much Console output after serverstop -->
  <Close_Window_on_Serverstop>true</Close_Window_on_Serverstop>
</root>
```

**Comment by suresttexas00** [comment]
OK.. sorry I missed that. 

Date: Sun, 7 Dec 2014 09:30:12 -0800

**Comment by suresttexas00** [comment]
OK it works fine now.. it's weird because I thought I just cut and pasted those options...  :)  I must've backed spaced over the M at some point

Date: Sun, 7 Dec 2014 09:30:12 -0800

**Comment by M4GNV5** [comment]
you can close this now i think ;)

**Comment by suresttexas00** [comment]
OK.. thanks!
