### ISSUE TITLE
uhh oh..?

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#10]
What's the deal with this?
        Server.RunCommand("tp "+_name+" ~ ~ ~");                Server.Instance.RunCommand("tp "+name+" ~ ~ ~"); 

Am I going to have to change my plugin code now?

**Comment by M4GNV5** [comment]
You cant really get the position of players by just reading the console output
the only possible way to do this is by teleporting him 0 blocks by X 0 by Y and 0 by Z (~ ~ ~)
NINSS will then read the position of this player and trigger the "PlayerPosition" event

**Comment by suresttexas00** [comment]
I was talking about the format of the command:

Server.RunCommand versus Server.Instance.RunCommand

**Comment by M4GNV5** [comment]
Ohh no there is no difference ^^
Instance is the static field of Server that always points to the server instance
so basically Server.Instance.Instance.Instance.Instance.RunCommand should still work

**Comment by suresttexas00** [comment]
So there IS a difference though..?   if you break that down a little for me?  May be very useful info on another issue I am having (no time to go into it now, but the reason I have a separate ".set" and ".sethome" command...

```
                  =
```

**Comment by M4GNV5** [comment]
you can do something like this:

``` javascript
var homes = {}; //associative array "homes"
//see this for more information about javascript "objects"
//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object
function ChatReceived(name, message)
{
    if(message.trim().toLowerCase() == ".sethome") //sethome command
    {
        homes[name] == "set"; //add player to setHome array
        Player.RefreshPosition(name); //same as Server.RunCommand("tp "+name+" ~ ~ ~");
    }
    else if(message.trim().toLowerCase() == ".home" && homes[name]) //check if player has a home
    {
        Server.RunCommand("tp "+name+" "+homes[name]); //tp player to home
    }
}
function PlayerPosition(name, position)
{
    if(homes[name] == "set") //if setHomePlayer 
    {
        homes[name] = position;
        Player.sendMessageTo(name, "Home set to "+position, "gold");
    }
}
```

so basically create a local variable that stores the home positions ;)

**Comment by suresttexas00** [comment]
That's good info on a few different things.  I can use the associative array idea to clean some code up and the .trim().toLowerCase() I did not know about to make the commands case-insensitive.. Thanks!

**Comment by suresttexas00** [comment]
right now all the player configs are stored in the files and accessed from there as required.

**Comment by suresttexas00** [comment]
This really did not have anything to do with the sethome problem (why I split it into separate commands).  I'll need some time to look this over and revisit that problem (which I put on the back burner because the current method works..)

**Comment by suresttexas00** [comment]
I guess we can close this.
