### ISSUE TITLE
UUID support, quick and dirty

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#12]
I added this to feed UUIDs to the chatreceived... it is flagged as not being "real" chat because the username is preceded by "!", so...
!SurestTexas00 <UUID>

from there, the chat routines can implement this in the plugin.

Here is what I added to MInecraftConnector.cs under ReadServerOutput:

```
        if (message.Contains("UUID of player"))
        {
            string[] split = message.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            string name = "!" + split[3];
            string chat = split[5];

            PlayerChatEventArgs eventArgs = new PlayerChatEventArgs(name, chat);
            TriggerEvent<PlayerChatEventArgs>(PlayerChatReceived, eventArgs);
        }
```

In the plugin, just checks for chat from "!<whoever>" to read the UUID.  I already have it working and I now store user config files by UUID.  further, (in the future) if someone changes their in-game name, all the settings will be preserved and the new name associated with the existing UUID is stored in the config file.

**Comment by suresttexas00** [comment]
Works pretty well.  I have the commands debugged, implemented the .sethome as you recommended using the array list, and have a full featured Permissions setup.

I set your LittleMagnus UUID to permission level 4 (everything)
players start at level 0 (they can only do .panic)
typing .panic promotes the player to level 1 (can sethome and home)
The .help menu is color coded and in order.

On the back end, all player configs are in a subfolder of Plugins and the filenames are <uuid>.xml format.

Can you add the code above to the project so that I can keep my version consistent with later changes you make?

**Comment by M4GNV5** [comment]
hmm i actually have a version here similar to yours (as its similar to the old UuidConnector)
but i am not quite sure...
maybe getting the uuids from the public mojang api or from the usercache.json file :no_mouth:

**Comment by suresttexas00** [comment]
I worked enough bugs out and moved it to my production server (I don't get many players) on port 25566

Date: Sat, 13 Dec 2014 15:27:50 -0800

**Comment by suresttexas00** [comment]
Do you want me to fork and pull request my version into the project?

**Comment by M4GNV5** [comment]
I am going to push mine soon.
I added the possibility for javascript plugins to make libraries like Config or Player, written in javascript, accesible for other (javascript) plugins. So i wrote the UUIDConnector in javascript as i want to have C# plugins only doing jobs that cannot be done in javascript

**Comment by suresttexas00** [comment]
:)
