### ISSUE TITLE
Config xml file formats

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#16]
I noticed that the NINSS xml file lines are terminated with a LF.  However, the config files written by  NINSS are terminated with CRLF.  Further, when NINSS saves a config file, if it was previously formatted with LFs, it replaces those with CRLF's.  Which way is correct?

**Comment by M4GNV5** [comment]
there isnt a "correct" way
according to wikipedia LF is linux, unix etc. so the NINSS.xml file seems to be LF as a wrote it using Sublime text what seems to use LF for line endings
The XmlReader from the .NET framework NINSS is using of course uses CRLF as .NET was made by Microsoft. So as long as both line endings can be read it doesnt matter what line endings you use. If you want to stick to conventions use CRLF as you are using windows :wink:
