### ISSUE TITLE
Simple plugin issues/questions

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#2]
Ok, I have now delved into testing and modifying the simple plugin.  I attemped the light command and nothing happened.  The problem appeared to be an incorrect usage of the setblock command.  So I added a console output to see what command it was attempting:
    Console.WriteLine("setblock "+position+" minecraft:torch");
    Server.RunCommand("setblock "+position+" minecraft:torch"); //set block where the player stands to a torch so the player has light

  Here are the results:

Name 'SurestTexas00' -c- 'light'
Teleported SurestTexas00 to 148.3381100525231, 64.0, 2782.7789860284024
setblock 148.3381100525231  minecraft:torch
Usage: /setblock <x> <y> <z> <TileName> [dataValue] [oldBlockHandling] [dataTag
Name 'x' --- 'Usage: /setblock  <y> <z> <TileName> [dataValue] [oldBlockHandling
] [dataTag'

The function is only passing the first coordinate and there is an extra space between the position and the itemname.  Can this be fixed from the plugin or does something else in NINSS need to be fixed.

Also, is it possible to:
1) not have the !'command' output to the chat?
2) Change the command character (I would like to use a period instead)

By the way, this is really awesome!  Simple but powerful at the same time!

**Comment by M4GNV5** [comment]
Yeah thats a bug :/
The way NINNS work is it uses the Minecraft output that is in the Console and uses it to e.g. when someone writes `!light` in the chat execute a javascript function. So no you cannot hide commands in the chat. The command is nothing more than the chat event (see https://github.com/M4GNV5/NINSS/blob/master/Examples/advancedJavascript.js#L62) so if you want to have e.g. a `§` for commands or nothing just use the ChatReceived "event" but note that `/` wont work.

The problem with the position is that NINNS was developed for Minecraft version 1.7.9 so it seems the output of Teleport Commands in the Console has changed between 1.79 and 1.8. I will take a look at it tomorrow and fix it :)

**Comment by suresttexas00** [comment]
Here are other errors from the console:
Loading Plugins!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\JavascriptConnec
tor.dll
Loading Javascript Plugins!
Loaded Javascript Plugin: simple.js
Finished Loading Javascript Plugins!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\Noesis.Javascrip
t.dll
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\SimplePermission
s.dll
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\UuidConnector.dl
l
Could not load Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\UuidConne
ctor.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the ta
rget of an invocation.
Stacktrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOn
ly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandle& ctor, Boolean& b
NeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean fillCach
e)
   at System.RuntimeType.CreateInstanceImpl(Boolean publicOnly, Boolean skipVisi
bilityChecks, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NINSS.PluginManager.LoadPlugin(String file)
InnerException: Name cannot begin with the '4' character, hexadecimal value 0x34
. Line 4, position 4.
Inner Stacktrace:
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset
, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese
rveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at NINSS.API.Config.LoadConfig(String name)
   at NINSS.API.Config..ctor(String name)
   at UuidConnector.UuidConnector.LoadUuids()
   at UuidConnector.UuidConnector..ctor()
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\WebUI.dll
Finished Loading Plugins!
Plugins: 3
Starting java with arguments: -Xmx1024M -Xmx1024M -jar "C:\Users\Minecraft\Deskt
op\NINSSVanilla\minecraft_server.1.8.1.jar" nogui
Starting minecraft server version 1.8.1
Loading properties

I am running the server on theimaginecraft.com:25575 if you want to see this running "in the wild".  I upgraded the basic plugin.  The commands all say type .help, .tpme, .tpto, etc... but use the ! as usual.  I did compile a new version using a period instead, but I am not using that version until all the bugs are worked out

Oh, yes.. also the write to console command writes to the console, but that writing never makes it to the server logs..?

Date: Sun, 7 Dec 2014 12:17:02 -0800

**Comment by M4GNV5** [comment]
This Error means you have a invalid config file for the UUID connector Plugin because one of the xml tags has a name starting with `4` what actually means your UUIDs.xml file has a node like `<4SomeOtherStuff>MinecraftName</4SomeOtherStuff>`. So this is another bug I didnt notice during NINNS development as my UUID starts with an `f`

Also note that if you are running a NINNS server "in the wild" you should defnitly remove the WebUI Plugin or block the port 8080 as otherwise everybody could harm your server as the WebUI requires no password etc.

**Comment by M4GNV5** [comment]
Haha i just joined your server got killed by an Enderman and then banned because its set to hardcore mode :laughing:

**Comment by M4GNV5** [comment]
The bug should be fixed now: https://github.com/M4GNV5/NINSS/commit/4ded852f723fe6e368e907cf55dcda6ddb9e1dd7
With the latest update i removed some features like uuid and permissions as i want to implement them using Javascript after i updated the api etc.
furthermore i wont publish a release yet so you would have to compile yourself if you want to use the newest version

**Comment by suresttexas00** [comment]
Yea, I just saw that.  I guess once you create and run a world as hardcore =true, it stays that way.  I started it several times now as hardcore=false and it still acts like hardcore.  I unbanned you and deleted your UUID file (fresh start)

Date: Mon, 8 Dec 2014 05:31:45 -0800

**Comment by suresttexas00** [comment]
NIce... and you are on a newer version of the compiler.  I was using 2013 and it had to convert the old stuff.

A recurring issue with the source, though; 
in the C# JavascriptConnector, the Noesis.Javascript reference is missing.  I cannot find it in your source files here, but it is included in a /lib directory.

Date: Mon, 8 Dec 2014 08:15:47 -0800

**Comment by suresttexas00** [comment]
Did you break my plugin, or do I have something else (improper build) going on here?  I noted that the "!" cannot be found in the source code now... did you abandon OnCommand??

Loading Plugins!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\JavascriptConnec
tor.dll
Loading Javascript Plugins!
Loading Plugin: C:\Users\Minecraft\Desktop\NINSSVanilla\plugins\simple.js
Process is terminated due to StackOverflowException.

Simple.Js:

function PlayerJoin(name) //PlayerJoin(name) is invoked when a player with name name joins the server
{
 Console.WriteLine("Player Join message sent to "+name+".");
 Player.SendMessageTo(name, "Hi, "+name+". Welcome to The Imagine Craft Vanilla server!", "gold");
 Player.SendMessageTo(name, "     Simple Plugin active!", "green");
 Player.SendMessageTo(name, "     To list Commands, type .help in chat.", "green");
 //"Simple Plugin active!\nto list Commands, type \"!H\" in chat:\n !tpto <player>,/n !tpme <player> \n !light\n\nThis Plugin has an anti-caps lock function!"
}
function PlayerLeave(name) //PlayerLeave(name) is invoked when a player with name name leaves the server
{
 Console.WriteLine("player "+name+" left the game");
 //Console.Beep(); //play a beep sound
}
function ChatReceived(name, message) //ChatReceived(name, message) is invoked when a Player says something
{
    //Console.WriteLine("Name '"+name+"' --- '"+message+"'");
    if (message.toUpperCase() == message && message.length > 3) //check if message is caps only and longer than 3 characters long
        {
        Server.RunCommand("kick " + name + " Please do not use caps lock!"); //kick player cause he used caps
        Console.WriteLine("[Simple] '" + name + "' was kicked for CAPS - '" + message + "'")
        }
}
function OnCommand(name, arg) //OnCommand(name, args) is invoked when a player says something beginning with a '.'
{
 Console.WriteLine("[Simple] Name '"+name+"' -c- '"+arg+"'");
 var args = arg.split(' '); //convert arg string to string array
 if (args[0] == "tpme") //check if command is 'tpme'
 {
     Server.RunCommand("tp " + args[1] + " " + name); //teleport sender to named player
     return;
 }

```
else if(args[0] == "tpto") 
    {//check if command is 'tpto'
  Server.RunCommand("tp "+name+" "+args[1]); //teleport named player to sender
     //else if(args[0] == "light") //check if command is 'light'
     // Server.RunCommand("tp "+name+" ~ ~ ~"); //you can use this command to call onPosition at the current position of //the player
     return;
    }
```

 else if (args[0] == "help")
     {//check if command is 'help'
         Player.SendMessageTo(name, "Simple Plugin Commands are typed into CHAT!...", "green");
         Player.SendMessageTo(name, "  .tpto <player> - teleport to player", "green");
         Player.SendMessageTo(name, "  .tpme <player> - teleport a player to you", "green");
         Player.SendMessageTo(name, "  .light - place a torch where you are standing.", "green");
         Player.SendMessageTo(name, "  .panic - Turn that hack client off... LOL", "green"); //list of commands
         return;
     }
 else if (args[0] == "sethome") //see if player want to goto spawn //not added to help yet
            {
      Server.RunCommand("spawnpoint "+name+" ~ ~ ~"); 
      Console.WriteLine("[Simple]EXECUTED: spawnpoint "+name+" ~ ~ ~");
      Player.SendMessageTo(name, "Bedspawn home set", "gold");
      return;
         }
 else if (args[0] == "panic") //the period is a popular hack client chat command prefix
         {
         Server.RunCommand("say How about that: looks like "+name+" passed the test and seems to be a legit player.");
         }
 else 
     {
         Player.SendMessageTo(name, "Command not recognized.  Type .help", "red");
         Console.WriteLine("[Simple] Player " + name + " attemped ." + args[0]+", which is not a valid command");
     }

}
function PlayerPosition(name, position) //PlayerPosition is invoked when a player is teleported to specific coordinates
{ //position is a ready to use string for command like tp or setblock (e. g. '10.3356 125.1234 46.6368')
 Console.WriteLine("EXECUTED: setblock "+position+" minecraft:torch");
 Server.RunCommand("setblock "+position+" minecraft:torch"); //set block where the player stands to a torch so the player has light
}
function ServerStart() //ServerStart() is invoked when the server starts
{
 Console.WriteLine("[Simple] - Simple Plugin active!"); //display message to server log

}
function ServerStop() //ServerStop() is invoked when the server stops
{
    //Console.Beep(); //note that if you play this too often java throws an exception cause it waited to long for the server Gui
    Console.WriteLine("[Simple] - Server down!"); //display message to server log
}

Date: Mon, 8 Dec 2014 08:15:47 -0800

**Comment by suresttexas00** [comment]
My simple.js did not cause the error, as I also tried your new advanced .js file.  I know I sent a few replies now, so I'll just do a summary here:
1) I like the new way of getting the commands using ChatReceived. and assume you did away with OnCommand..
2) Need to track down the "Process is terminated due to StackOverflowException." that now prevents me from running NINSS.
3) Noesis.Javascript reference is missing in the C# JavascriptConnector

4) Lastly, when I compile the project, am I correct that I only need to get the new 
NINSS.exe and JavascriptConnector.dll
?? - I ask because the following files are also created and I'm not sure what thay are for/what to do with them:
JavascriptConnector.csprojResolveAssemblyReference.cache
JavascriptConnector.csproj.FileListAbsolute.txt
NINSS.csproj.FileListAbsolute.txt

I guess, to say... what are the contents and folders of a release build?

 -Once these are addressed, I will then close out this thread and continue testing.

**Comment by M4GNV5** [comment]
Okay in chronological order:
1) Yeah OnCommand does not exist anymore
2) i dont know exactly why you get that one i will take a look at it tomorrow as its 9:30pm for me now :blush:
3) you can download noesis.javascript binaries at http://javascriptdotnet.codeplex.com/releases/view/88504 or just use the Noesis.Javascript file you downloaded with the 0.3 binaries of NINSS.
4) what do you use for compiling? at the moment i deactivated WebUI as its not updated for the latest NINSS updates. If it tells you you are missing Noesis.Javascript just remove and readd the reference (left click at references in visual and xamain studio)

The contents of a release build is just the NINSS.exe a plugins folder containing a JavascriptConnector.dll and a config folder containing a NINSS.xml (that you need to copy from the 0.3 binaries)

**Comment by M4GNV5** [comment]
PS your server is still hardcore and i am dead again :laughing:  :laughing:  :laughing:

**Comment by suresttexas00** [comment]
I know and I can't change it (evidently) unless I dig in further into the world folder.... I don't know which file is holding that attribute yet, but it is ignoring the server.properties setting.

Date: Mon, 8 Dec 2014 12:23:40 -0800

**Comment by suresttexas00** [comment]
using Microsoft Visual studio community 2013

Date: Mon, 8 Dec 2014 12:19:45 -0800

**Comment by suresttexas00** [comment]
I rebuilt the server world as regular mode and I have the new NINSS running fine... the plugin, well that's a new thread :)
