### ISSUE TITLE
syntax error in plugin example

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#4]
I believe this statement should be Args not Arg:

```
else if(arg[0] == ".welcome_refresh") //if command is 'welcome_refresh'
    RefreshValues(); //refresh the variables
```

**Comment by suresttexas00** [comment]
The whole program is functional including the plugin... come check it out.  "not on hardcore this time" :D

**Comment by M4GNV5** [comment]
yeah you are right :relaxed:
and next time if you find an error you can fork & fix it & create a pull request :stuck_out_tongue_winking_eye:

**Comment by M4GNV5** [comment]
fixed: https://github.com/M4GNV5/NINSS/commit/877ff9432634d493338ed938a57074e217ddea21
