### ISSUE TITLE
Legacy support of functions

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#7]
Ok, now that I have started to write plugins on this system, it occurs to me that things like removing the OnCommand function, even if there is a better way to do it, should not be done.  Once a function is available, it should be supported for the life of the project.  This way, users do not have to re-write what could end up being pretty lengthy plugins.  OnCommand, I guess, would be the exception, since it appears I am the only one using this so far.. ?

**Comment by M4GNV5** [comment]
OnCommand was just useless it forced people to use `!` as their command key and and didnt had more information than ChatReceived

Furthermore as OnCommand was just a normal Javascript function in your code, if you want to use an old plugin you could just add code looking something like this to your ChatReceived function:

``` javascript
if(message[0] == '!') //check if the first letter is !
{
    //call the OnCommand function
    OnCommand(name, message.substring(1)); 
}
```

of course if you want to use e.g. `.` as a command key you can replace the '!' with '.'
