### ISSUE TITLE
Why does it start twice?

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#8]
Why does NINSS start in the cmd window, start the GUI (I removed -nogui, but it was still doing this with the single cmd window); the world loads, then both windows close and then open back up again?  I noticed I can login when the first set of windows loads, but then get kicked during the flicker as it reloads the second time..

**Comment by suresttexas00** [comment]
It has been going this from the very beginning, but it was only an annoyance in light of the other issues...

**Comment by M4GNV5** [comment]
so you get two windows at the beginning? both close and then reopen?
or do you get one window that reopens after some time?

and actually i have no idea why this could happen ^^ do you have a startscript? or do you launch the NINSS.exe directly?

**Comment by suresttexas00** [comment]
How many windows depends on how I start it (gui or nogui).  and yes, the window(s) close once the world is finished loading and then immediately re-open after that.

I start NINSS directly with no script (Am I supposed to?)

```
                  =
```

**Comment by M4GNV5** [comment]
no your not ^^
but sorry i really have no idea why it does that :/
it may be a bug with your .net runtime or something else

**Comment by suresttexas00** [comment]
I really will not have any further info on this.. I suppose it should be closed until/unless someone else has an issue.
